#include "RandomDice.h"
#include <random>

#include <iostream>

int RandomDice::getRandomFace()
{		
	static std::random_device rd;  //Will be used to obtain a seed for the random number engine					
	static std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	
	// Since the variable is static, dis is created only once - the first time code flows over it
	static std::uniform_int_distribution<> dis(1, 6);

	//Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
	return dis(gen);
}




